trigger:
- master

pool:
    vmImage: 'vs2017-win2016'

variables:
    solution: '*/.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Debug'
    enableCustomProcessTemplate: true
    customWorkItemType: 'Bug'
    customPTActiveStatus: 'In Progress'
    customPTNewStatus: 'New'
    customPTResolvedStatus: 'Resolved'
    customPTCloseStatus: 'Closed'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'add'
    arguments: '$(build.sourcesDirectory) package Microsoft.CodeAnalysis.FxCopAnalyzers --version 2.9.3'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'add'
    arguments: '$(build.sourcesDirectory) package Microsoft.CodeAnalysis.VersionCheckAnalyzer --version 2.9.3'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'add'
    arguments: '$(build.sourcesDirectory) package Microsoft.CodeQuality.Analyzers --version 2.9.3'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'add'
    arguments: '$(build.sourcesDirectory) package Microsoft.NetCore.Analyzers --version 2.9.3'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'add'
    arguments: '$(build.sourcesDirectory) package Microsoft.NetFramework.Analyzers --version 2.9.3'
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation=$(build.artifactStagingDirectory)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
